platform :ios, '15.0'

target 'OTG' do
  use_frameworks!

  # Core dependencies
  pod 'Alamofire', '~> 5.7'
  pod 'SwiftyJSON', '~> 5.0'

  # Networking and security
  pod 'KeychainAccess', '~> 4.2'

  target 'OTGTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
