package org.unfpa.otg.knowledge

import android.content.Context
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import org.unfpa.otg.db.AppDatabase
import org.unfpa.otg.db.FormularyEntry
import org.unfpa.otg.db.KnowledgeChunk
import org.unfpa.otg.db.KnowledgeDoc

/**
 * KnowledgeRepository — loads knowledge/index.json from assets on first use,
 * populates Room, and delegates vector search to VectorSearch.
 *
 * index.json is generated by scripts/precompute-android-assets.ts and contains
 * all chunk text, citation metadata, and a parallel vectors.bin binary file for
 * pre-computed embeddings.
 */
class KnowledgeRepository(
    private val context: Context,
    private val embeddingEngine: EmbeddingEngine,
    private val vectorSearch: VectorSearch,
) {
    private val db = AppDatabase.getInstance(context)
    private val json = Json { ignoreUnknownKeys = true }

    @Serializable
    data class IndexChunk(
        val chunkId: String,
        val docSlug: String,
        val chunkIndex: Int,
        val content: String,
        val contentHash: String,
        val documentTitle: String,
        val vertical: String,
        val sourceDocument: String = "",
        val sourceEdition: String = "",
        val sourceSection: String = "",
        val sourcePage: Int = 0,
        val sourceUrl: String = "",
        val verbatimExcerpt: String = "",
        val expiryDate: String? = null,
        val language: String = "en",
    )

    @Serializable
    data class IndexFile(
        val version: String,
        val generatedAt: String,
        val chunkCount: Int,
        val chunks: List<IndexChunk>,
    )

    data class SearchResult(
        val chunkId: String,
        val documentTitle: String,
        val docSlug: String,
        val content: String,
        val sourcePage: Int,
        val sourceSection: String,
        val sourceDocument: String,
        val sourceUrl: String,
        val verbatimExcerpt: String,
        val expiryDate: String?,
        val score: Float,
    )

    private var initialised = false

    suspend fun initialise() = withContext(Dispatchers.IO) {
        if (initialised) return@withContext
        if (db.knowledgeChunkDao().count() == 0) {
            loadAssetsIntoDb()
        }
        vectorSearch.load(db.knowledgeChunkDao().getAll())
        initialised = true
    }

    private suspend fun loadAssetsIntoDb() {
        val indexJson = context.assets.open("knowledge/index.json")
            .bufferedReader().readText()
        val index = json.decodeFromString<IndexFile>(indexJson)

        val docs = mutableMapOf<String, KnowledgeDoc>()
        val chunks = mutableListOf<KnowledgeChunk>()

        // Load embedding vectors from binary file (Float32LE, 384 dims per chunk)
        val vectorsBytes = context.assets.open("embeddings/vectors.bin").readBytes()
        val floatBuf = java.nio.ByteBuffer.wrap(vectorsBytes)
            .order(java.nio.ByteOrder.LITTLE_ENDIAN)
            .asFloatBuffer()

        index.chunks.forEachIndexed { i, c ->
            docs.getOrPut(c.docSlug) {
                KnowledgeDoc(
                    slug = c.docSlug,
                    title = c.documentTitle,
                    vertical = c.vertical,
                    contentHash = c.contentHash,
                    expiryDate = c.expiryDate,
                    sourceUrl = c.sourceUrl.ifBlank { null },
                    language = c.language,
                    ingestedAt = System.currentTimeMillis(),
                )
            }

            val embeddingBytes = ByteArray(384 * 4)
            val floatSlice = FloatArray(384)
            floatBuf.position(i * 384)
            floatBuf.get(floatSlice, 0, 384)
            java.nio.ByteBuffer.wrap(embeddingBytes)
                .order(java.nio.ByteOrder.LITTLE_ENDIAN)
                .asFloatBuffer()
                .put(floatSlice)

            chunks.add(KnowledgeChunk(
                chunkId = c.chunkId,
                docSlug = c.docSlug,
                chunkIndex = c.chunkIndex,
                content = c.content,
                contentHash = c.contentHash,
                embedding = embeddingBytes,
                sourceDocument = c.sourceDocument,
                sourceEdition = c.sourceEdition,
                sourceSection = c.sourceSection,
                sourcePage = c.sourcePage,
                sourceUrl = c.sourceUrl,
                verbatimExcerpt = c.verbatimExcerpt,
                expiryDate = c.expiryDate,
                language = c.language,
                ingestedAt = System.currentTimeMillis(),
            ))
        }

        db.knowledgeDocDao().upsertAll(docs.values.toList())
        db.knowledgeChunkDao().upsertAll(chunks)
    }

    suspend fun search(
        query: String,
        topK: Int = 5,
        verticals: List<String> = emptyList(),
    ): List<SearchResult> = withContext(Dispatchers.Default) {
        val queryEmbedding = embeddingEngine.embed(query)
        val rawResults = vectorSearch.search(queryEmbedding, topK * 3) // over-fetch, then filter

        val filtered = if (verticals.isEmpty()) rawResults else {
            rawResults.filter { r ->
                verticals.any { v ->
                    // MOH_MMR matches "MOH_MMR" vertical, or "MOH" prefix wildcard
                    r.vertical == v || (v.startsWith("MOH_") && r.vertical == v)
                }
            }
        }

        filtered.take(topK).map { r ->
            SearchResult(
                chunkId = r.chunkId,
                documentTitle = r.documentTitle,
                docSlug = r.docSlug,
                content = r.content,
                sourcePage = r.sourcePage,
                sourceSection = r.sourceSection,
                sourceDocument = r.sourceDocument,
                sourceUrl = r.sourceUrl,
                verbatimExcerpt = r.verbatimExcerpt,
                expiryDate = r.expiryDate,
                score = r.score,
            )
        }
    }

    suspend fun chunkExists(chunkId: String): Boolean = withContext(Dispatchers.IO) {
        db.knowledgeChunkDao().getById(chunkId) != null
    }

    suspend fun getChunk(chunkId: String): KnowledgeChunk? = withContext(Dispatchers.IO) {
        db.knowledgeChunkDao().getById(chunkId)
    }

    /**
     * Semantic clinical search with embedding-based vector similarity.
     * Used for general clinical queries, symptom-based searches, and guideline lookups.
     */
    suspend fun searchClinical(
        query: String,
        topK: Int = 5,
    ): List<SearchResult> = withContext(Dispatchers.Default) {
        search(query, topK, verticals = emptyList())
    }

    /**
     * Search for clinical guidelines for a specific condition.
     * Performs semantic search on condition name and returns relevant guideline chunks.
     */
    suspend fun getClinicalGuidelines(condition: String): List<SearchResult> =
        withContext(Dispatchers.Default) {
            val query = "clinical guidelines for $condition management triage assessment"
            search(query, topK = 10, verticals = emptyList())
                .filter { result ->
                    // Filter for guideline-like content
                    result.content.lowercase().contains("guideline")
                        || result.content.lowercase().contains("management")
                        || result.content.lowercase().contains("protocol")
                }
        }

    /**
     * Look up drug information from the formulary.
     * Returns the first matching drug entry by exact or partial name match.
     */
    suspend fun getDrugInfo(drugName: String): FormularyEntry? = withContext(Dispatchers.IO) {
        val normalised = drugName.lowercase().trim()
        db.formularyDao().getAll().firstOrNull { entry ->
            entry.drug.equals(normalised) ||
            entry.genericName.lowercase().equals(normalised) ||
            entry.drug.contains(normalised) ||
            entry.genericName.lowercase().contains(normalised)
        }
    }

    /**
     * Get all available citations for a specific chunk.
     * Returns source metadata including document, section, page, URL, and verbatim excerpt.
     */
    suspend fun getCitations(chunkId: String): List<Citation> = withContext(Dispatchers.IO) {
        val chunk = db.knowledgeChunkDao().getById(chunkId) ?: return@withContext emptyList()
        listOf(
            Citation(
                chunkId = chunk.chunkId,
                sourceDocument = chunk.sourceDocument,
                sourceEdition = chunk.sourceEdition,
                sourceSection = chunk.sourceSection,
                sourcePage = chunk.sourcePage,
                sourceUrl = chunk.sourceUrl,
                verbatimExcerpt = chunk.verbatimExcerpt.ifBlank { chunk.content.take(300) },
                expiryDate = chunk.expiryDate,
                language = chunk.language,
            )
        )
    }

    data class Citation(
        val chunkId: String,
        val sourceDocument: String,
        val sourceEdition: String,
        val sourceSection: String,
        val sourcePage: Int,
        val sourceUrl: String,
        val verbatimExcerpt: String,
        val expiryDate: String?,
        val language: String,
    )

    /**
     * Get all knowledge chunks for offline RAG (Retrieval-Augmented Generation).
     * Used to build context for clinical queries.
     */
    suspend fun getAllChunks(): List<KnowledgeChunk> = withContext(Dispatchers.IO) {
        db.knowledgeChunkDao().getAll()
    }

    /**
     * Search with hybrid approach: semantic + keyword matching.
     * Combines vector similarity with BM25-style keyword relevance.
     */
    suspend fun searchHybrid(
        query: String,
        topK: Int = 5,
        keywordWeight: Float = 0.3f,
        semanticWeight: Float = 0.7f,
    ): List<SearchResult> = withContext(Dispatchers.Default) {
        // Get semantic results
        val semanticResults = search(query, topK * 2, verticals = emptyList())

        // Apply keyword matching on semantic results
        val keywords = query.lowercase().split(Regex("\\s+"))
        val reranked = semanticResults.map { result ->
            val keywordMatches = keywords.count { keyword ->
                result.content.lowercase().contains(keyword)
            }
            val keywordScore = (keywordMatches.toFloat() / keywords.size) * keywordWeight
            val semanticScore = result.score * semanticWeight
            result.copy(score = semanticScore + keywordScore)
        }
            .sortedByDescending { it.score }
            .take(topK)

        reranked
    }

    /**
     * Get chunks by vertical (e.g., "MOH_PCPNC", "WHO_MCH").
     * Useful for scoping searches to specific clinical guidelines.
     */
    suspend fun getChunksByVertical(vertical: String): List<SearchResult> =
        withContext(Dispatchers.IO) {
            db.knowledgeChunkDao().getAll()
                .filter { chunk ->
                    // Match vertical from sourceDocument or other metadata
                    chunk.sourceDocument.contains(vertical) ||
                    chunk.docSlug.contains(vertical)
                }
                .map { chunk ->
                    SearchResult(
                        chunkId = chunk.chunkId,
                        documentTitle = chunk.sourceDocument.ifBlank { chunk.docSlug },
                        docSlug = chunk.docSlug,
                        content = chunk.content,
                        sourcePage = chunk.sourcePage,
                        sourceSection = chunk.sourceSection,
                        sourceDocument = chunk.sourceDocument,
                        sourceUrl = chunk.sourceUrl,
                        verbatimExcerpt = chunk.verbatimExcerpt,
                        expiryDate = chunk.expiryDate,
                        score = 1.0f, // No scoring for vertical filter
                    )
                }
        }
}
